"""agragacion columnas de relacion en inscripcion

Revision ID: 0ff3bb0171e8
Revises: 7720c381a832
Create Date: 2025-07-10 16:09:13.556374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff3bb0171e8'
down_revision: Union[str, None] = '7720c381a832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscripcion', 'equipo',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='testpublic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscripcion', 'equipo',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='testpublic')
    # ### end Alembic commands ###
