"""primer modelo

Revision ID: 34c9848927d2
Revises: 
Create Date: 2025-06-17 16:41:22.385432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c9848927d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('pais_aso', sa.Text(), nullable=False),
    sa.Column('ciudad_aso', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo'], ['testpublic.equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=True),
    sa.Column('edad_max', sa.Integer(), nullable=True),
    sa.Column('genero_categoria', sa.Text(), nullable=False),
    sa.Column('sets_partido', sa.Integer(), nullable=True),
    sa.Column('puntos_sets', sa.Integer(), nullable=True),
    sa.Column('equipo', sa.Boolean(), nullable=True),
    sa.Column('inscripcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion'], ['testpublic.inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero_jugador', sa.Text(), nullable=False),
    sa.Column('pais_jugador', sa.Text(), nullable=False),
    sa.Column('ciudad_jugador', sa.Text(), nullable=False),
    sa.Column('asociacion', sa.Integer(), nullable=True),
    sa.Column('equipo', sa.Integer(), nullable=False),
    sa.Column('inscripcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asociacion'], ['testpublic.asociacion.id'], ),
    sa.ForeignKeyConstraint(['equipo'], ['testpublic.equipo.id'], ),
    sa.ForeignKeyConstraint(['inscripcion'], ['testpublic.inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('fecha_inscrip', sa.Date(), nullable=True),
    sa.Column('mesas_disp', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.Text(), nullable=False),
    sa.Column('inscripcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion'], ['testpublic.inscripcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('categoria_torneo',
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('torneo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['testpublic.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo'], ['testpublic.torneo.id'], ),
    sa.PrimaryKeyConstraint('categoria', 'torneo'),
    schema='testpublic'
    )
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_fase', sa.Text(), nullable=False),
    sa.Column('nombre_fase', sa.Text(), nullable=False),
    sa.Column('torneo', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['testpublic.categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo'], ['testpublic.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignado', sa.Boolean(), nullable=True),
    sa.Column('torneo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['torneo'], ['testpublic.torneo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('fase_jugador',
    sa.Column('fase', sa.Integer(), nullable=False),
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fase'], ['testpublic.fase.id'], ),
    sa.ForeignKeyConstraint(['jugador'], ['testpublic.jugador.id'], ),
    sa.PrimaryKeyConstraint('fase', 'jugador'),
    schema='testpublic'
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_partido', sa.Text(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('mesas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesas'], ['testpublic.mesas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    op.create_table('categoria_partido',
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('partido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['testpublic.categoria.id'], ),
    sa.ForeignKeyConstraint(['partido'], ['testpublic.partido.id'], ),
    sa.PrimaryKeyConstraint('categoria', 'partido'),
    schema='testpublic'
    )
    op.create_table('jugador_partido',
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.Column('partido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador'], ['testpublic.jugador.id'], ),
    sa.ForeignKeyConstraint(['partido'], ['testpublic.partido.id'], ),
    sa.PrimaryKeyConstraint('jugador', 'partido'),
    schema='testpublic'
    )
    op.create_table('jugador_partido_2',
    sa.Column('jugador', sa.Integer(), nullable=False),
    sa.Column('partido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador'], ['testpublic.jugador.id'], ),
    sa.ForeignKeyConstraint(['partido'], ['testpublic.partido.id'], ),
    sa.PrimaryKeyConstraint('jugador', 'partido'),
    schema='testpublic'
    )
    op.create_table('resultado_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido', sa.Integer(), nullable=False),
    sa.Column('num_set', sa.Text(), nullable=False),
    sa.Column('jugador_1', sa.Text(), nullable=False),
    sa.Column('jugador_2', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['partido'], ['testpublic.partido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='testpublic'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_set', schema='testpublic')
    op.drop_table('jugador_partido_2', schema='testpublic')
    op.drop_table('jugador_partido', schema='testpublic')
    op.drop_table('categoria_partido', schema='testpublic')
    op.drop_table('partido', schema='testpublic')
    op.drop_table('fase_jugador', schema='testpublic')
    op.drop_table('mesas', schema='testpublic')
    op.drop_table('fase', schema='testpublic')
    op.drop_table('categoria_torneo', schema='testpublic')
    op.drop_table('torneo', schema='testpublic')
    op.drop_table('jugador', schema='testpublic')
    op.drop_table('categoria', schema='testpublic')
    op.drop_table('inscripcion', schema='testpublic')
    op.drop_table('equipo', schema='testpublic')
    op.drop_table('asociacion', schema='testpublic')
    # ### end Alembic commands ###
