"""cambio en inscripcion de nullable a true

Revision ID: 7720c381a832
Revises: b5a914bfca41
Create Date: 2025-07-03 16:00:07.700955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7720c381a832'
down_revision: Union[str, None] = 'b5a914bfca41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscripcion', 'equipo',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='testpublic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscripcion', 'equipo',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='testpublic')
    # ### end Alembic commands ###
