"""cambio tabla asociacion

Revision ID: b59706ac9665
Revises: 34c9848927d2
Create Date: 2025-06-19 17:33:30.933285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59706ac9665'
down_revision: Union[str, None] = '34c9848927d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asociacion', 'pais_aso', schema='testpublic')
    op.drop_column('asociacion', 'ciudad_aso', schema='testpublic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asociacion', sa.Column('ciudad_aso', sa.TEXT(), autoincrement=False, nullable=False), schema='testpublic')
    op.add_column('asociacion', sa.Column('pais_aso', sa.TEXT(), autoincrement=False, nullable=False), schema='testpublic')
    # ### end Alembic commands ###
