"""agregacion pais y ciudad en aso

Revision ID: b5a914bfca41
Revises: 5ca7b1beddc2
Create Date: 2025-07-03 11:55:48.528971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a914bfca41'
down_revision: Union[str, None] = '5ca7b1beddc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asociacion', sa.Column('pais_aso', sa.Text(), nullable=False), schema='testpublic')
    op.add_column('asociacion', sa.Column('ciudad_aso', sa.Text(), nullable=False), schema='testpublic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asociacion', 'ciudad_aso', schema='testpublic')
    op.drop_column('asociacion', 'pais_aso', schema='testpublic')
    # ### end Alembic commands ###
